################################################################################
# 
# Objet : File to set up the netwok with docker with the other config file
#     
# version : 2
#
# Author : Rêzan OSCAR
#
# Infos :
#   - Be careful with the environement varible of the CLI
# 
################################################################################


version: '2'

volumes:
  orderer.research-network.com:
  peer0.pro1.research-network.com:
  peer0.pro2.research-network.com:
  peer0.pro3.research-network.com:
  peer0.pro4.research-network.com:
  peer0.pro5.research-network.com:


networks:
  byfn:

services:

  orderer.research-network.com:
    extends:
      file:   docker/docker-compose.yaml
      service: orderer.research-network.com
    container_name: orderer.research-network.com
    networks:
      - byfn

  peer0.pro1.research-network.com:
    container_name: peer0.pro1.research-network.com
    extends:
      file:  docker/docker-compose.yaml
      service: peer0.pro1.research-network.com
    networks:
      - byfn

  
  peer0.pro2.research-network.com:
    container_name: peer0.pro2.research-network.com
    extends:
      file:  docker/docker-compose.yaml
      service: peer0.pro2.research-network.com
    networks:
      - byfn

  peer0.pro3.research-network.com:
    container_name: peer0.pro3.research-network.com
    extends:
      file:  docker/docker-compose.yaml
      service: peer0.pro3.research-network.com
    networks:
      - byfn
      
  peer0.pro4.research-network.com:
    container_name: peer0.pro4.research-network.com
    extends:
      file:  docker/docker-compose.yaml
      service: peer0.pro4.research-network.com
    networks:
      - byfn

  peer0.pro5.research-network.com:
    container_name: peer0.pro5.research-network.com
    extends:
      file:  docker/docker-compose.yaml
      service: peer0.pro5.research-network.com
    networks:
      - byfn
 
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    dns_search: .
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.pro1.research-network.com:7051
      - CORE_PEER_LOCALMSPID=Research1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/fabric-samples/research-network/crypto-config/peerOrganizations/pro1.research-network.com/peers/peer0.pro1.research-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/fabric-samples/research-network/crypto-config/peerOrganizations/pro1.research-network.com/peers/peer0.be.research-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/fabric-samples/research-network/crypto-config/peerOrganizations/pro2.research-network.com/peers/peer0.pro2.research-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/fabric-samples/research-network/crypto-config/peerOrganizations/pro2.research-network.com/users/Admin@pro2.research-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/chain
        - ./crypto-config:/opt/gopath/fabric-samples/research-network/crypto-config/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/fabric-samples/research-network/channel-artifacts

    depends_on:
      - orderer.research-network.com
      - peer0.pro1.research-network.com
      - peer0.pro2.research-network.com
      - peer0.pro3.research-network.com
      - peer0.pro4.research-network.com
      - peer0.pro5.research-network.com

    networks:
      - byfn


